### ISSUE TITLE
Can't find any users.

### ISSUE THREAD

**Issue by Ruq6** [FedeIlLeone/Tnym-js#6]
**"@ doesn't exist on tellonym" error on every user.** 
![image](https://user-images.githubusercontent.com/120338660/209976126-3f38002b-521e-41da-b5d7-9714f407fca2.png)

**Comment by FedeIlLeone** [comment]
Thank you for the report 👍🏻. I found the problem, it seems they made it that you now need to pass in the request headers the user-agent. I will apply a fix in the next few hours.

**Comment by Ruq6** [comment]
![image](https://user-images.githubusercontent.com/120338660/210105031-a6f5ee8e-3816-4a0d-9bdc-0cade030b300.png)
Hello!

I don't know if it's me but I reinstalled it, wanted to try it and got this message again.
I appreciate your work very much and used your tool in spring 2022, it worked well there.
I wish you a happy new year, celebrate well!

**Comment by FedeIlLeone** [comment]
Whoops sorry I didn't publish the actual release (v2.4.5), you can download the new version now. If everything is fine I'll close this issue. Thank you!

**Comment by Ruq6** [comment]
> Whoops sorry I didn't publish the actual release (v2.4.5), you can download the new version now. If everything is fine I'll close this issue. Thank you!

It works for me now, thx! Is there any way to bypass the ratelimit_reached?

**Comment by FedeIlLeone** [comment]
Use proxies to bypass that limit. You need good ones, which most of the time are paid. When I used the free proxies you find online, the tool doesn't work very well. I should experiment in the future if you can bypass the rate limit by having multiple accounts.
